### ISSUE TITLE
Requires some more guidance

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/galaxy-example-arc#1]
Just tested this out of curiosity. 

1. In the readme "and checkout the `galaxy_integration` branch" probably means there is another branch in addition to `master`? 
I just ran `git checkout -b galaxy_integration`. 

2. I followed the remaining instructions and eventually got `INFO Final process status is success`. There was no output (files?). What can I expect to see?

**Comment by ZimmerA** [comment]
Hi, thanks for checking this out!

For 1.: This is a remainder from when this was still in the Hackathon_samplerun repository I have factored this out since then and forgot to change the readme as it seems... There is just the master branch 😀 

For 2.: The resulting data is in the run/run1/history folder. It is already in there when pulling this repository, I should probably put a notice somwhere for that or remove the folder from the repository.
For now, you can delete the history folder and try again!

**Comment by ZimmerA** [comment]
I updated the README, please re-open if there are any further problems regarding this!

**Comment by Brilator** [comment]
Works perfectly. Thanks!
